apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notes-app
  template:
    metadata:
      labels:
        app: notes-app
    spec:
      containers:
      - name: notes-app
        image: satyamsri/notes-app:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: notes-data
          mountPath: /data
      volumes:
      - name: notes-data
        persistentVolumeClaim:
          claimName: notes-pvc

ubuntu@ip-172-31-33-3:~/notes-app/k8s$ cat pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: notes-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
